### PR TITLE
Added Python 3.13 support

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #64 

----
📚 Documentation preview 📚: https://mocksafe--67.org.readthedocs.build/en/67/

### CODE REVIEW

**Comment by Brijeshthummar02** [comment]
@dmayo3 go through the pr.

**Review by dmayo3 — COMMENTED** [review]
@Brijeshthummar02 thanks for contributing! 

The changes look good. Only issue is that now I've approved the builds to run, the 3.13 build is failing with an error in the sphinx documentation build step. There's also an error about a missing dependency. 

I don't know what is wrong exactly, but it could be because 3.13 is quite new and perhaps sphinx doesn't fully support it yet. 

Feel free to take a look at the error and see if you can figure out the problem, or I can maybe take a closer look at it when I have the time.

**Comment by Brijeshthummar02** [comment]
@dmayo3 any update?

**Comment by Brijeshthummar02** [comment]
@dmayo3 done!
this pr is good to go with merge.

**Pull request merged**
